---
version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    volumes:
      - jenkins_volume:/var/jenkins_home
    ports:
      - 8989:8080
      - 50050:50000
    networks:
      - multi-compose-net
      - external-compose-net
  nexus:
    image: sonatype/nexus3:latest
    volumes:
      - nexus_volume:/nexus-data
    ports:
      - 8990:8081
    #environment:
    #  - INSTALL4J_ADD_VM_PARAMS="-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m"


volumes:
  jenkins_volume:
    driver: local
  nexus_volume:
    driver: local

networks:
  multi-compose-net:
    driver: bridge
  external-compose-net:
    external: true